### ISSUE TITLE
Does this work? 

### ISSUE THREAD

**Issue by nrmitchi** [gogiel/marionette.loading#4]
I've been trying to get this to work but have been having prototype problems; ie, `setupMarionetteLoading` undefined on CompositeView, ItemView, etc.

Any advice?

**Comment by gogiel** [comment]
Hello @nrmitchi. It looks like this lib has problems with new Marionette. Some methods are missing (or renamed). I'll fix it soon.
Thank you for your feedback.

**Comment by gogiel** [comment]
@nrmitchi current master should work with new Marionette.
Please be shure that `setupMarionetteLoading` is called inside `initialize` method of your view.

**Comment by nrmitchi** [comment]
Mhmm unfortunately I still can't get this to work properly.

The main problem I'm running into is that setupMarionetteLoading() is undefined.

Do you have a working example of this in action?

**Comment by gogiel** [comment]
@nrmitchi https://www.dropbox.com/s/965k12b69bukcrj/marionette.loading-example.zip?dl=0

**Comment by nrmitchi** [comment]
I'm getting a 404 on that

**Comment by gogiel** [comment]
@nrmitchi fixed. Sorry, no idea how it got deleted from my Dropbox.
